### ISSUE TITLE
Ripple-client not working

### ISSUE THREAD

**Issue by TOCONSULT** [jatchili/minimalist-ripple-client#25]
Trying to use:: https://jatchili.github.io/minimalist-ripple-client/

It will not connect to ripple, have used this client software for a year without issues,

Now it is not working. Is this a RIPPLE problem or minimalist Problem ???

Could this issue related to the current ripple ledger issues which are increasing the ripple / xrp fees ???

Any help or observation would be appreciated.

thanks, a long time user of GITHUB

**Comment by TOCONSULT** [comment]
Everything AccFan23 says below is far beyond me, 

IS THERE ANYTHING YOU CAN DO TO HELP ME.

PLEASE,  I HAVE NO WHERES ELSE TO TURN.

Paul

 AccFan23 commented 2 hours ago

I could be wrong here but it seem there's some new changes on the Ripple side:

When trying to connect it gets back:

error: "reportingUnsupported"
error_code: 91
error_message: "Requested operation not supported by reporting mode server"

Doing some googling that with leads to:
https://ripple.github.io/rippled/ErrorCodes_8cpp_source.html where we see that same error so moving to another google with the error name takes us to:

https://xrpl.org/blog/2021/rippled-1.8.1.html in the change log from 6 days ago they say:

Reporting mode supports validations and manifests streams: In the API it is now possible to connect to these streams when connected to a servers running in reporting. Previously, attempting to subscribe to these streams on a reporting server failed with the error reportingUnsupported.

I haven't seen any new dev activity on this Minimalist wallet in years so if something needs to be updated on the Minimalist wallet side, don't hold your breath.

**Comment by TOCONSULT** [comment]
Again, thank you for your consideration..

I verified my XRP on bithomp.com/explorer. It shows the exchange, all the transactions of when I created the wallet. It also shows unregistered.

If I have the XRP address and secret code, can I access them using another app or exchange?

Paul

**Comment by TOCONSULT** [comment]
Found XUMM under RippleLabs, can import my wallets from MINIMALIST into XUMM, completed successfully.

CLOSE THIS PROBLEM,, Thanks

**Comment by TOCONSULT** [comment]
Close

**Comment by LuitzenH** [comment]
> Trying to use:: https://jatchili.github.io/minimalist-ripple-client/
> 
> It will not connect to ripple, have used this client software for a year without issues,
> 
> Now it is not working. Is this a RIPPLE problem or minimalist Problem ???
> 
> Could this issue related to the current ripple ledger issues which are increasing the ripple / xrp fees ???
> 
> Any help or observation would be appreciated.
> 
> thanks, a long time user of GITHUB

Can you please reopen this issue. Since it is still not connecting other users may have the same issue. This needs to be fixed. probably a API end thing that is changed?

**Comment by bmafma10** [comment]
Hello, 

I found a solution,
Here what you need to do:
- After downloading the **minimalist ripple client** edit the "index.html" file with a text editor i prefer Notepad++
- Look for line: "**wss://s-west.ripple.com:443**" i think its in line 225, we need to edit the 2 lines 225 and 226
- Replace this address "_wss://s-west.ripple.com:443_" by this "**wss://xrplcluster.com:443**"
- Replace this address "_wss://s-east.ripple.com:443_" by this "**wss://xrpl.ws:443**"
- Save your file index.html
- Now try to connect and it will connect successfully 

I hope this solution is what you seek for.
